### ISSUE TITLE
APIConnectionError

### ISSUE THREAD

**Issue by swayampragnya-malla** [jeffrey-fong/Invoker#5]
i am getting APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79bdb1a1e2c0>: Failed to establish a new connection: [Errno 111] Connection refused')) issue while running the scripts.
Is there any way to fix it?????

**Comment by jeffrey-fong** [comment]
Hi,

Actually, I have stopped maintaining this project and I would like to recommend another great function-calling chat model (I'm part of the team/org working on it) if you are interested in trying out. It is finetuned on much more diverse data than Invoker, on better pretrained models like Mistral, and also greater server-side support.

[https://github.com/MeetKai/functionary](https://github.com/MeetKai/functionary)
[https://huggingface.co/meetkai/functionary-7b-v1.4](https://huggingface.co/meetkai/functionary-7b-v1.4)

Thank you.

**Comment by swayampragnya-malla** [comment]
Thank you for response ,i will try https://github.com/MeetKai/functionary
